os: linux
dist: bionic
language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2"
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: jPidXJwGLKcbW7In6YdTUtaN/qmgovVJ1sQkUE0rHSMwfvISNdTi/ssDpWbUhMXvTfyEj3kEl4aJfUgyL+b7sfkWnNuV6JaakgT3XdZTA9hy7ccu1NAkpIRQPI+mMf2XkN7J2RyPn/SiuJtaab0oZEDUzBdje7oTHRMAD7VrSyDQDzv1ou5pvjF2+gsu+vf/+3trloCRV15mO9AB3XLFY3QjhffNaHQT6a+KaU7p1pOcnAywSzaS3jcf/rzzgk4HhKU6VIeo+IP69ijpODLY8j2DfUiSnko0IDwThOou2gimQu/VdmPR0S4UuzifryuNeTzspyNHSCwDOFBbdQ9nNqk+eAP4PnuY5FfZc9oNqL7ii3vdzSDU/fuAPBtei3V6TDFQXcvCAxLt5Ee5u7NfHXDJKt5p8dQgr0Qh87NkF/96e0d1KUf1EGyndd+cvyXniFG6556dNYdbozGEd9EGOVrTadoWIGqMvaNiMRVKKWJKgG4rPm/kvJ+XVxwGR7HfetiZWs5JXI3jNUHq2pek/2xjHzLGOeQrVYUoIE6LRnFkvs06UtN0GSRJrNyS6Hh+3MpUhaR1yPMlZuhhLMMqdaoXHLmxtrmAXtt8/A6kS1W4i+H5CwmlpfGmZvcbZjww5RNqh09qKQY1A4Kchr17vBlXYWAhNYOimSDTUtdxQtE=
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vkgl-vcf-converter
deploy:
  provider: releases
  api_key:
    secure: C503EIdcuXUA50a2Ky93PWjxYDiZqvJ8KslRtpBsmBTQrJvS32VPkHDIzOTXJBygT6on91twuQ1e+6aRkFfuCYx5QM0o3H0h96LcudR1rGTL85yCqPs1WPVNbf7nz+wZ4cg2YRBiiCLUYOorAdxhD7adnU3LbscJkNSfg2Vjr28ZopcbaRrcmTVzUxD4xHa+ddj6wslwPhUaXl2hI1EitVdCyl2LDnyGypj1+lJBfQaQPAnmcvcbbhJiEmC/RT1hja6bVgDxK8qS5CfQUkXdiBkUieqsDeOJSJi7XG87qtqFq/GQgpC46leD2oTdK3JzCi857KzV3G9W8DYN/TTArDrMmomy0wLlPW9J1R9JD+nrZqzTj1s1C1HjNBnqFDsNCFf9g7duYXbPptNTA63mgifniXhZ3PK+t34RoqaeeHDQGHkoZGR5P31dQvATc/jHWCimPki344zBasseLCuKrLuycrDHS1f07KL9Nw/rYszEki52DnOQQSfzroQDZb2Edr9ATixBRW1DWJgpDxUziSfmUnnfGhTrqPpk2XrdkRxsSGwtlav2dhyM1jQC2LMA+yhODLvx5ypvsPeEKLsODWc/9Dm8wH/pc4xCL4Ln6tDY/vOqGR7swebSot6ZsnKCXPZVjucOr0D73IhV7K9WtZA0Hypj1FyF2P5DHWJ7syc=
  file: target/vkgl-vcf-converter.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
