os: linux
dist: bionic
language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2"
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: jPidXJwGLKcbW7In6YdTUtaN/qmgovVJ1sQkUE0rHSMwfvISNdTi/ssDpWbUhMXvTfyEj3kEl4aJfUgyL+b7sfkWnNuV6JaakgT3XdZTA9hy7ccu1NAkpIRQPI+mMf2XkN7J2RyPn/SiuJtaab0oZEDUzBdje7oTHRMAD7VrSyDQDzv1ou5pvjF2+gsu+vf/+3trloCRV15mO9AB3XLFY3QjhffNaHQT6a+KaU7p1pOcnAywSzaS3jcf/rzzgk4HhKU6VIeo+IP69ijpODLY8j2DfUiSnko0IDwThOou2gimQu/VdmPR0S4UuzifryuNeTzspyNHSCwDOFBbdQ9nNqk+eAP4PnuY5FfZc9oNqL7ii3vdzSDU/fuAPBtei3V6TDFQXcvCAxLt5Ee5u7NfHXDJKt5p8dQgr0Qh87NkF/96e0d1KUf1EGyndd+cvyXniFG6556dNYdbozGEd9EGOVrTadoWIGqMvaNiMRVKKWJKgG4rPm/kvJ+XVxwGR7HfetiZWs5JXI3jNUHq2pek/2xjHzLGOeQrVYUoIE6LRnFkvs06UtN0GSRJrNyS6Hh+3MpUhaR1yPMlZuhhLMMqdaoXHLmxtrmAXtt8/A6kS1W4i+H5CwmlpfGmZvcbZjww5RNqh09qKQY1A4Kchr17vBlXYWAhNYOimSDTUtdxQtE=
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vkgl-vcf-converter
deploy:
  provider: releases
  api_key:
    secure: Uhg/JiAlYYRkER1dUsVP370QAH030fWnep5D3Qe+6GJYhyiXzhfmc3T3vF9k4i8sI4P7qbEaYxkTzo0VuH6oNavqL1nE++N2hFXZn7Un14NnONJDZl78dSHGRXHQNZJVmCx3Iv3bC3MeKwWpR8rtCchAvu3z9wpHkmOWxZqjXf8dcdwb3rZFj8PoG4JmgpxkEhJH5JFJ3UR/MGQGO8ySQqBHMXLpMV+HnwVSkzT8p4EHVxEFL6uFz9Unqw9XndTovOzSGdk+wQEGJ4fl7bGsVJlSqycpg48iOV79MaKCViS5zmuWPtShdZroVcC1CgOw/5GkrM1kfQ1eIqkNIyRm5FwNRyktTyECvRyYhtW2i4tEBm2fXSP+0AzbL5HtfTVRgq2rT3H3wfwJHy4IKT2gQSkOH9XUCuP5YwkbbstBecYl8MlNDXADNRIXmycFXpioEYg9nvGIKtpgJwcEjvRjxsd8B0S/skNAODLSmoyhn2nBsV+yK9FvT9PS7qngZbKDPCMb2jMFR79yrYjdp6+YrldfPmkZW9WaaMA8ec6+3MIxuj+Veja86QmqcjKE5CC09b+/Y5YxwPGBKAUQES/UTzDc9AzmXB/idnkhfY2cD+6+lEsiO7VPXEPTpFQaTes28eg5mEsRhTKZZXcgMBui1rfjpXFsDwlFv4KEoyPvZQ0=
  file: target/vkgl-vcf-converter.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
